#pragma once
#include "Core/Base.h"
#include "Core/Layer.h"
#include "Core/Application.h"
#include "Math/Matrix.h"
#include "Renderer/SceneRenderer.h"
#include "Scene/Scene.h"
#include "Scene/SceneLoader.h"
#include <GL/freeglut.h>
#include "Renderer/Sample.h"